sungwon2598/moya

front/src/App.tsx, front/src/component/Feature.tsx, front/src/context/AuthContext.tsx, front/src/layout/RootLayout.tsx, front/src/layout/header/Header.tsx, front/src/layout/header/NavItem.tsx, front/src/main.tsx, front/src/pages/main/Main.tsx, front/src/pages/main/MainContent.tsx, front/src/routes/index.tsx, front/src/types/types.tsx, front/tailwind.config.js, front/tsconfig.app.json
메인 페이지 UI 구현 및 로그인/로그아웃 상태에 따른 조건부 렌더링 기능 추가
- 메인 페이지 레이아웃 구현
- 인증 상태에 따른 UI 분기 처리
- 라우팅 및 전역 상태 관리 구조 설정
- React Router를 활용한 라우팅 구조 설정
- Root Layout 구현
- 메인, 로그인, 회원가입 라우트 설정
- 전역 인증 상태 관리를 위한 Context API 구현
- AuthContext 및 useAuth 훅 구현
- 로그인/로그아웃 상태 관리 기능
- MainContent 컴포넌트 구현
- 반응형 디자인 적용
- 로그인/비로그인 상태별 UI 분기
- Tailwind CSS를 활용한 스타일링
- 주요 기능 컴포넌트 구현
- 헤더 레이아웃
- 액션 버튼 그리드 (로그인 상태)
- 회원가입 및 로그인 CTA (비로그인 상태)
https://tonggangag.atlassian.net/browse/KAN-76?atlOrigin=eyJpIjoiNTczMDAwMWFmYTFiNDRjMDgwOWJiYTVjNWFiNDhiOTAiLCJwIjoiaiJ9
#3 
- 새로운 의존성 추가
- react-router-dom: 라우팅 관리 https://github.com/sungwon2598/moya/wiki/%5BFE%5D-%EB%9D%BC%EC%9A%B0%ED%8A%B8-%EC%84%A4%EC%A0%95-%EB%B0%A9%EB%B2%95
- lucide-react: 아이콘 컴포넌트
- tailwindcss: 스타일링
- AuthContext를 사용하는 모든 컴포넌트는 Provider 내부에 위치해야 합니다.
```
메인 …
```
=> #3 KAN-76 메인페이지 UI

front/src/context/ModalContext.tsx
깃 파일 추가시 ModalContext.tsx 컴포넌트 누락하여 추가하였음
=> KAN-86 fix: 컨텍스트 킷 커밋에 포함

front/package.json, front/src/data/footerData.ts, front/src/index.css, front/src/layout/RootLayout.tsx, front/src/layout/footer/Footer.tsx, front/src/layout/footer/FooterComponents.tsx, front/src/layout/footer/FooterSection.tsx, front/src/layout/footer/footerData.ts, front/src/types/footer.ts
모든 페이지에서 사용할 footer 구현
- 제목과 항목들을 하나의 섹션으로 묶음 (FooterSection.tsx)
- 각각의 항목과 소셜 미디어 아이콘은 링크로 되어 있음 (FooterComponents.tsx)
- 텍스트 기반의 내부 페이지 링크 (FooterLink)
- 아이콘 기반의 소셜 미디어 링크 (SocialLink)
- 각 섹션에 들어갈 데이터들은 정적인 요소이므로 data 폴더에 .ts 파일로 관리
- 푸터 컴포넌트 구현
- 반응형 디자인 적용
- 섹션 컴포넌트화
https://tonggangag.atlassian.net/browse/KAN-87?atlOrigin=eyJpIjoiMjVjOGUyN2VkODBlNDU5OWFmZjYzODM3ODI5NGZmMDkiLCJwIjoiaiJ9
* 전역 스타일에 background-color 추가 (bg-gray-50)
* 헤더 영역만큼 페이지 상단 여백 추가 (페이지 잘림 방지)
* 새로운 의존성 추가
* lucide-react: 아이콘 컴포넌트(없어져서 다시 추가)
```
src/
├── layout/
│   └── footer/
│       ├── Footer.tsx           # 푸터의 최상위 컴포넌트
│       ├── FooterComponents.tsx # 푸터에서 사용되는 재사용 컴포넌트
│       └── FooterSection.tsx    # 푸터의 각 섹션 컴포넌트
├── data/
│   └── footerData.ts           # 푸터 데이터
└── types/
└── footer.ts …
```
=> KAN-87--footer

back/moya/src/main/java/com/study/moya/Oauth/controller/OAuthController.java
=> KAN-94 feat : Uri 변경

.github/workflows/frontend-deploy.yml
- GitHub Actions workflow 추가
- frontend 디렉토리 변경 시에만 동작하도록 설정
- S3 자동 배포 설정
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_REGION
- AWS_S3_BUCKET
- VITE_TEST_DATA
1. frontend 디렉토리 내 파일 수정
2. PR 생성
3. Actions 탭에서 워크플로우 실행 확인
4. S3 배포 완료 확인
=> KAN-102 feat: fe deploy yml 파일 추가

.github/workflows/frontend-deploy.yml, front/package.json
=> KAN-102 fix: ts 타입 체크 스크립트 추가 및 적용

.github/workflows/frontend-deploy.yml, front/package.json
=> KAN-102 fix: 빌드 오류 설정 수정

.github/workflows/frontend-deploy.yml
=> KAN-102 fix: 잘못된 git 변수명 수정

back/moya/src/main/java/com/study/moya/Oauth/handler/OAuth2AuthenticationSuccessHandler.java
success handler 기능 수정
- 
- 
- 
Close #50 API 통신기능 설정
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-105 fix. API로 통신하도록 수정

back/moya/src/main/java/com/study/moya/chat/config/StompChannelInterceptor.java, back/moya/src/main/java/com/study/moya/chat/config/WebSocketStompConfig.java, back/moya/src/main/java/com/study/moya/chat/message/ChatType.java, back/moya/src/main/java/com/study/moya/chat/message/hadnler/ChatMessageHandler.java, back/moya/src/main/java/com/study/moya/chat/message/hadnler/ChatMessageHandlerManager.java, back/moya/src/main/java/com/study/moya/chat/message/hadnler/JoinMessageHandler.java, back/moya/src/main/java/com/study/moya/chat/message/hadnler/LeaveMessageHandler.java, back/moya/src/main/java/com/study/moya/chat/message/hadnler/MessageHandler.java, back/moya/src/main/java/com/study/moya/chat/text/controller/TextChatController.java, back/moya/src/main/java/com/study/moya/chat/text/controller/TextChatRoomController.java, back/moya/src/main/java/com/study/moya/chat/text/dto/chat/ChatDTO.java, back/moya/src/main/java/com/study/moya/chat/text/dto/chat/MessageType.java, back/moya/src/main/java/com/study/moya/chat/text/dto/chatroom/ChatRoomDTO.java, back/moya/src/main/java/com/study/moya/chat/text/dto/chatroom/ChatRoomType.java, back/moya/src/main/java/com/study/moya/chat/text/service/ChatService.java, back/moya/src/main/java/com/study/moya/chat/text/service/MemberChatService.java, back/moya/src/main/java/com/study/moya/member/domain/Member.java
Close #56 
Chat부분과 Member엔티티 오류 수정
=> KAN-109--ConfigError

.github/workflows/backend-deploy.yml, back/moya/Dockerfile
도커파일 추가
도커파일 추가
백엔드 루트 경로에 도커파일 추가 
- Close #59 
도커파일 수정 필요시 토의 진행
추후 공지
=> Hotfix docker

front/src/core/types/profile.ts, front/src/features/profile/EditProfile.tsx, front/src/shared/components/profile/ProfileForm.tsx
=> KAN-114 fix: EditProfile.tsx 타입 오류 개선

front/.env.development, front/.env.production, front/src/features/auth/api/authApi.ts
=> KAN-114 hotfix: .env 구글 클라이언트 id 변경

back/moya/src/main/java/com/study/moya/global/config/security/SecurityConfig.java, back/moya/src/main/java/com/study/moya/member/service/MemberService.java, back/moya/src/main/java/com/study/moya/posts/dto/post/PostListResponse.java, back/moya/src/main/java/com/study/moya/posts/repository/LikeRepository.java, back/moya/src/main/java/com/study/moya/posts/service/CommentService.java, back/moya/src/main/java/com/study/moya/posts/service/LikeService.java, back/moya/src/main/java/com/study/moya/posts/service/PostService.java
긴급 : 이전 PR 에러 fix 및 시큐리티 수정(영진님과 협업 완)
=> Kan 115  posts

back/moya/src/main/java/com/study/moya/global/config/OpenApiConfig.java
=> feat : 스웨거 cors 에러

front/.env.development, front/package-lock.json, front/package.json, front/src/App.tsx, front/src/core/config/apiConfig.ts, front/src/core/config/studyApiConfig.ts, front/src/features/auth/api/authApi.ts, front/src/features/auth/components/GoogleLoginButton.tsx, front/src/features/auth/components/ProtectedRoute.tsx, front/src/features/auth/hooks/useAuth.ts, front/src/features/auth/store/authSlice.ts, front/src/features/auth/types/auth.types.ts, front/src/features/auth/types/global.d.ts, front/src/features/layout/header/Header.tsx, front/src/features/layout/header/components/usermenu/UserDropdown.tsx, front/src/features/profile/EditProfile.tsx, front/src/pages/main/MainContent.tsx, front/src/pages/study/StudyList.tsx, front/src/pages/study/StudyPostDetail.tsx, front/src/pages/study/studyMockData.ts
구글 oauth 로그이 로직 구현
- 구글 authorizaion 코드 발급 
- 스프링 부트 post 로그인요청
- 응답받은 내용으로 Redux 상태관리
=> KAN-124-OAuth-Refactor

front/src/App.tsx
=> KAN-124 fix: 잘못된 배포 수정

front/src/features/auth/store/authSlice.ts
=> KAN-124 fix: 배포 오류로 재배포

front/.env.production, front/src/core/providers/context/ModalContext.tsx
=> KAN-124 fix: 배포 오류로 재배포 2

front/src/features/auth/components/GoogleLoginButton.tsx, front/src/features/auth/types/auth.types.ts, front/src/features/auth/types/global.d.ts
=> Kan 124 o auth refactor

front/src/features/auth/components/GoogleLoginButton.tsx
=> KAN-124 fix: 타입 체크

back/moya/src/main/java/com/study/moya/oauth/controller/TestControllerr.java
=> KAN-125 BugFix. test 1

back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java
=> KAN-125 BugFix. test 2

back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java
=> KAN-125 BugFix. test 3

back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java
=> KAN-125 BugFix. test 4

back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java
=> KAN-125 BugFix. test 5

back/moya/src/main/java/com/study/moya/auth/jwt/JwtTokenProvider.java, back/moya/src/main/java/com/study/moya/oauth/controller/LoginController.java, back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java
refreshToken, logout 로직 완성
refreshToken 재발급(RTR 기능 유지), logout시 블랙리스트 토큰 발급
- 
- 
- 
#98 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-126 feat. refreshToken, logout logic

back/moya/src/main/java/com/study/moya/oauth/controller/LoginController.java, back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-127 fix. uri 통합 수정 + 탈퇴 기능 추가

back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-127 bug fix. 통합 uri 버그 수정

back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-127 bug fix. 통합 uri 버그 수정2

back/moya/src/main/java/com/study/moya/oauth/controller/LoginController.java, back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-127 bug fix. 통합 uri 버그 수정3

front/src/core/config/studyApiConfig.ts
=> KAN-124 chore: 임시 배포

front/src/features/auth/api/authApi.ts
=> KAN-124 fix: 배포시 이전 코드 적용됨

front/package-lock.json, front/package.json, front/src/App.tsx, front/src/core/config/roadmapApiConfig.ts, front/src/features/auth/hooks/useAdmin.ts, front/src/features/auth/store/authSlice.ts, front/src/features/roadmap/RoadmapPreview.tsx, front/src/pages/create-sample/CreateRoadmapModal.tsx, front/src/pages/create-sample/CreateSample.tsx, front/src/pages/create-sample/SerchBox.tsx, front/src/pages/create-sample/ViewRoadmapModal.tsx, front/src/pages/create-sample/types.ts, front/src/pages/main/MainContent.tsx, front/src/pages/main/MainPage.tsx
로드맵 샘플 제작 페이지를 모달 형식으로 추가
* 샘플 제작 모달 추가
* 카테고리 선택시 검색 기능 추가
https://tonggangag.atlassian.net/browse/KAN-128?atlOrigin=eyJpIjoiOWFjMjMzODBjMTU2NGVhY2E2MjExYzYyYTRkY2IxZDEiLCJwIjoiaiJ9
* es-hangul: 초성 검색 기능을 위해 추가
=> KAN-128-create-sample

front/src/pages/adminator/assets/styles/index.scss, front/src/pages/adminator/layout/AdminLayout.tsx, front/src/pages/hot-study/HotStudy.tsx, front/src/pages/hot-study/HotStudyCard.tsx, front/src/pages/hot-study/hotStudyMockData.ts, front/src/pages/main/MainPage.tsx, front/src/shared/hooks/useSlideControl.ts, front/src/shared/utils/dateUtils.ts
메인 페이지 최하단에 hot 스터디 컴포넌트 추가
hot 스터디 페이지 추가 
https://tonggangag.atlassian.net/browse/KAN-131?atlOrigin=eyJpIjoiOWQ5OTUzMjZlNDIyNGQzZThkYTgyNWYwNzQ2NGFkNGMiLCJwIjoiaiJ9
없음
새로 추가된 패키지 없음
기본 상태
마우스를 올렸을 때
현재 hot 스터디에 들어간 내용들은 목업 데이터로 구성되어 있음 추후 수정해야함
=> KAN-131-hot-study

front/src/App.tsx, front/src/features/layout/header/Header.tsx, front/src/features/layout/header/components/usermenu/UserDropdown.tsx, front/src/pages/create-sample/CreateSample.tsx
프로필 메뉴에 내 로드맵, 내 관심 로드맵 항목 추가
안쓰는 import 및 함수 주석처리 및 제거
* 기존에 cicd 과정에서 발생하던 타입체크 오류 수정
https://tonggangag.atlassian.net/browse/KAN-130?atlOrigin=eyJpIjoiNjFiNjM0NTkzN2JjNDcyYTg0ODczYjRlZTcyMmRiYjYiLCJwIjoiaiJ9
* cicd 정상화
* 없음
내 로드맵, 내 관심 로드맵 상세페이지는 구현 필요
=> Kan 130 my page

front/src/features/layout/header/components/usermenu/UserMenu.tsx
프로필 메뉴에 내 로드맵, 내 관심 로드맵 항목 추가
안쓰는 import 및 함수 주석처리 및 제거
* 기존에 cicd 과정에서 발생하던 타입체크 오류 수정
https://tonggangag.atlassian.net/browse/KAN-130?atlOrigin=eyJpIjoiNjFiNjM0NTkzN2JjNDcyYTg0ODczYjRlZTcyMmRiYjYiLCJwIjoiaiJ9
* cicd 정상화
* 없음
내 로드맵, 내 관심 로드맵 상세페이지는 구현 필요
=> KAN-130 refactor: UserDropdown import 방식 수정

back/moya/build.gradle, back/moya/src/main/java/com/study/moya/auth/domain/RefreshToken.java, back/moya/src/main/java/com/study/moya/auth/exception/UserNotFoundException.java, back/moya/src/main/java/com/study/moya/auth/jwt/JwtTokenProvider.java, back/moya/src/main/java/com/study/moya/auth/repository/RefreshTokenRepository.java, back/moya/src/main/java/com/study/moya/member/service/MemberService.java, back/moya/src/main/java/com/study/moya/oauth/service/OauthService.java, back/moya/src/main/java/com/study/moya/redis/RedisService.java
jwt 수정에 따른 메서드 수정
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> feat. jwt 수정(sub값을 email -> id), 이에 따라 refreshToken, oauth 수정

front/src/features/layout/header/components/usermenu/UserDropdown.tsx
=> KAN-130 feat: UserDropdown 메뉴에서 관리자일 경우에만 카테고리 관리, 샘플 제작 메뉴 추가

back/moya/src/main/java/com/study/moya/global/api/ApiResponse.java
공통 API 코드 wiki에 맞춰 수정
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-129. bug fix. 공통 API 코드 수정

back/moya/build.gradle, back/moya/src/main/java/com/study/moya/global/api/ApiResponse.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-129. bug fix. 공통 API 코드 수정2

back/moya/src/main/java/com/study/moya/oauth/controller/LoginController.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-129 fix. 공통 API 수정에 따른 OAuth 수정1

back/moya/src/main/java/com/study/moya/oauth/controller/LoginController.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-129 fix. 공통 API 수정에 따른 OAuth 수정2

back/moya/src/main/java/com/study/moya/redis/RedisService.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-133 feat. OAuth swagger 및 코드 정리2

front/src/features/auth/hooks/useAdmin.ts, front/src/features/layout/header/components/usermenu/UserDropdown.tsx, front/src/pages/auth/SignInPage.tsx, front/src/pages/main/MainContent.tsx, front/src/pages/profile/ProfilePage.tsx, front/vite.config.ts
fix
user.roles 속성에 대한 예외처리
- userDropdown.tsx
- useAdmin.ts
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-140-test_jin

front/src/features/auth/hooks/useAdmin.ts
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-154-어드민-접속권한

front/package-lock.json, front/package.json, front/postcss.config.js, front/src/index.css, front/tailwind.config.js, front/vite.config.ts
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-161-테일윈드-업그레이드

front/package-lock.json, front/src/components/shared/ui/calendar.tsx, front/src/index.css, front/src/pages/study/studyMockData.ts, front/tailwind.config.js
스터디 목업 데이터 타입 수정
studies, studyDetails 배열 변경
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-165-study-data-type-check

.github/workflows/backend-deploy.yml
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> Kan 141 관리자 페이지 개발

back/moya/src/main/java/com/study/moya/admin/controller/AdminMemberController.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-141 bugfix. 로그 권한 설정 테스트

.github/workflows/backend-deploy.yml, back/moya/src/main/java/com/study/moya/admin/controller/AdminMemberController.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-141 bugfix. 로그 권한 설정 테스트2

.github/workflows/backend-deploy.yml, back/moya/src/main/java/com/study/moya/admin/controller/AdminMemberController.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-141 bugfix. 로그 권한 설정 테스트3

back/moya/src/main/java/com/study/moya/ai_roadmap/controller/RoadmapController.java, back/moya/src/main/java/com/study/moya/ai_roadmap/service/RoadmapService.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-168 feat. AI 사용시 토큰 사용 기능 추가

back/moya/src/main/java/com/study/moya/oauth/controller/LoginController.java, back/moya/src/main/java/com/study/moya/oauth/dto/auth/OAuthLoginResponse.java, back/moya/src/main/java/com/study/moya/oauth/service/GoogleOAuthService.java, back/moya/src/main/java/com/study/moya/oauth/service/MemberOAuthService.java, back/moya/src/main/java/com/study/moya/oauth/service/OAuthFacadeService.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-177 ref. OAuth 로직 수정 및 최적화

front/index.html, front/src/App.tsx, front/src/components/roadmap/Select/ChoseKeyword.tsx, front/src/components/roadmap/Select/Select.tsx, front/src/features/roadmap/api/createRoadmap.ts, front/src/features/roadmap/hooks/useRoadmapQuestions.ts, front/src/index.css, front/src/pages/roadmap/CreatePage.tsx, front/src/pages/roadmap/RoadmapPending.tsx, front/src/pages/roadmap/WeeklyPlan.tsx, front/tailwind.config.js
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> Kan 170 로드맵 생성 1 5

front/src/components/roadmap/Select/ChoseKeyword.tsx, front/src/features/roadmap/hooks/useRotatingMessage.ts, front/src/index.css, front/src/pages/roadmap/RoadmapPending.tsx, front/src/pages/roadmap/WeeklyPlan.tsx
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-170 create week plan page

front/src/components/roadmap/Select/ChoseKeyword.tsx, front/src/core/config/apiConfig.ts, front/src/features/roadmap/api/createRoadmap.ts, front/src/pages/roadmap/RoadmapPending.tsx, front/src/pages/roadmap/WeeklyPlan.tsx
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-170 create week plan page get data

front/src/components/roadmap/Select/ChoseKeyword.tsx, front/src/components/roadmap/Select/Select.tsx, front/src/features/roadmap/RoadmapPreview.tsx, front/src/features/roadmap/hooks/useRoadmapQuestions.ts
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-170 로드맵 생성 제한

front/src/components/layouts/header/Header.tsx, front/src/components/layouts/header/components/usermenu/UserDropdown.tsx
로그인 유저 드롭다운 컴포넌트 오류 수정
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> 드롭다운 오류 수정

back/moya/src/main/java/com/study/moya/oauth/controller/LoginController.java, back/moya/src/main/java/com/study/moya/oauth/dto/auth/OAuthLoginRequest.java, back/moya/src/main/java/com/study/moya/oauth/dto/auth/OAuthLoginResponse.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-184 ref. credential 삭제 + jwt json전송

front/src/App.tsx, front/src/api/authApi.ts, front/src/components/features/study/list/card/index.tsx, front/src/core/config/studyApiConfig.ts, front/src/pages/study/StudyPostDetail.tsx, front/src/pages/study/edit/index.tsx
1. 재화 확인을 위한 마이페이지 생성 (/my-info)
2. 게시글 삭제 및 수정
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-185-마이페이지

front/src/components/features/roadmap/Progress.tsx
로드맵 progress.tsx 타입 수정
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> fix roadmap progress

front/src/App.tsx, front/src/components/features/study/list/card/index.tsx, front/src/core/config/studyApiConfig.ts, front/src/pages/hot-study/HotStudy.tsx, front/src/pages/hot-study/HotStudyCard.tsx, front/src/pages/study/StudyPostDetail.tsx, front/src/shared/hooks/useSlideControl.ts, front/src/shared/utils/dateUtils.ts, front/src/store/auth.ts
최대 10개 표시
게시글 이동
토큰 만료시 로그아웃
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-188 핫 게시글

front/src/components/features/profile/profileForm/index.tsx, front/src/core/types/profile.ts, front/src/pages/my-info/MyPage.tsx, front/src/store/auth.ts
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> update: mypage:

front/vite.config.ts
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-190 fix: css

back/moya/src/main/java/com/study/moya/oauth/service/MemberOAuthService.java, back/moya/src/main/java/com/study/moya/oauth/service/OAuthFacadeService.java
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> hotfix. login redis문제로 임시처리

front/src/components/features/main/RoadmapPreview.tsx, front/src/components/features/roadmap/RotatingMessage.tsx, front/src/components/features/roadmap/Select/ChoseKeyword.tsx, front/src/components/features/roadmap/Select/Select.tsx, front/src/components/features/roadmap/WeeklyPlan/WeeklyPlanCard.tsx, front/src/components/layouts/header/Header.tsx, front/src/components/shared/ui/progress.tsx, front/src/features/roadmap/api/createRoadmap.ts, front/src/pages/main/MainContent.tsx, front/src/pages/main/MainPage.tsx, front/src/pages/my-info/Roadmap/MyRoadmap.tsx, front/src/pages/my-info/Roadmap/RoadmapDetail.tsx, front/src/pages/roadmap/CreatePage.tsx, front/src/pages/roadmap/RoadmapPending.tsx, front/src/pages/roadmap/WeeklyPlan.tsx
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> Kan 182 로드맵 마이페이지

front/src/components/features/roadmap/WeeklyPlan/WeeklyPlanCard.tsx, front/src/features/myinfo/api/getRoadmap.ts, front/src/pages/roadmap/WeeklyPlan.tsx
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> fix:type err

front/src/components/features/roadmap/RotatingMessage.tsx, front/src/components/features/roadmap/Select/Select.tsx, front/src/pages/my-info/MyPage.tsx, front/src/pages/my-info/Roadmap/MyRoadmap.tsx, front/src/pages/my-info/Roadmap/RoadmapDetail.tsx
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> feat: myroadmap detail

front/src/components/features/auth/hooks/useAuth.ts, front/src/components/layouts/header/Header.tsx, front/src/components/layouts/header/components/usermenu/UserDropdown.tsx, front/src/store/auth.ts, front/src/types/auth.types.ts, front/src/utils/tokenUtils.ts
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-198 update: login callback

front/src/App.tsx, front/src/components/features/auth/store/authSlice.ts, front/src/components/layouts/footer/Footer.tsx, front/src/pages/main/MainContent.tsx, front/src/pages/my-info/MyPage.tsx, front/src/pages/study/detail/StudyPostDetail.tsx, front/src/pages/study/studyMockData.ts, front/src/store/store.ts
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> KAN-199 update: 스토어정리

front/src/features/roadmap/api/createRoadmap.ts, front/src/pages/roadmap/CreatePage.tsx
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> test:axios url

front/src/features/roadmap/api/createRoadmap.ts
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> fix:api url

front/src/features/roadmap/api/createRoadmap.ts, front/src/pages/my-info/Roadmap/RoadmapDetail.tsx
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> fix : worksheet param

front/src/features/roadmap/api/createRoadmap.ts
- 
- 
- 
- 설명 추가
- 해결 방법 설명
- 검토 결과
- 적용 방안
```sql
-- SQL 구문 작성
```
-
- 
- 
-
=> fix : params
